management:
  security:
    roles: ADMIN

---
spring:
  profiles: development

web:
  statics:
    js-bundle-location: https://localhost:3000/petfinder-site.js

---
spring:
  profiles: qa

web:
  statics:
    js-bundle-location: /statics/petfinder-site.js
    css-bundle-location: /statics/petfinder-site.css
