stages:
  - build
  - test
  - deploy

gradleBuild:
  image: gradle:4.1
  stage: build
  script:
    - gradle build
    
herokuDeploy:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/afternoon-thicket-12402.git
    - git push heroku master
    - echo "Deployed to heroku server"
  only:
    - master