
stages:
  - init
  - build
  - test
  - deploy

init:
  image: node:8.5.0
  stage: init
  script:
    - npm install

gradleBuild:
  image: gradle:4.1
  stage: build
  script:
    - gradle build
    
herokuDeploy:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$e09a579b-06b9-4a1f-b199-8466320ca939@git.heroku.com/afternoon-thicket-12402.git
    - git push heroku master
    - echo "Deployed to heroku server"
  only:
    - master