image: node:8.5.0

stages:
  - init
  - build
  - test
  - deploy

init:
  stage: init
  script:
    - npm install

gradleBuild:
  stage: build
  script:
    - chmod +x gradlew
    - ./gradlew build
    
herokuDeploy:
  stage: deploy
  script:
    - git remote add heroku https://git.heroku.com/afternoon-thicket-12402.git
    - git push heroku master
    - echo "Deployed to heroku server"
  only:
    - master